LuckLogsApp/Models/RaidLog.cs
using System;
using System.Data.Entity;
using System.Web;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Configuration;

namespace LuckLogsApp.Models
{
    public class RaidLog
    {
        public int ID { get; set; }
        public string EVTCFile { get; set; }
        public string HtmlFile { get; set; }
        public string BossName { get; set; }
        public bool Sucess { get; set; }
        public DateTime Date { get; set; }
        public TimeSpan KillTime { get; set; }
        public string CompTable { get; set; }
        public string killDate { get; set; }
        public int uploaderID { get; set; }
        public int relRate { get; set; }
        public int groupID { get; set; }
    }

   
    public class RaidLogDBContext : DbContext {
        public RaidLogDBContext() : base(GetRDSConnectionString()) { }
        //  public static RaidLogDBContext Create() { return new RaidLogDBContext(); }
        public DbSet<RaidLog> RaidLogs { get; set; }
       
        public static string GetRDSConnectionString()
        {
            var appConfig = ConfigurationManager.AppSettings;

            string dbname = appConfig["RDS_DB_NAME"];

            if (string.IsNullOrEmpty(dbname)) return null;

            string username = appConfig["RDS_USERNAME"];
            string password = appConfig["RDS_PASSWORD"];
            string hostname = appConfig["RDS_HOSTNAME"];
            string port = appConfig["RDS_PORT"];

            return "Data Source=" + hostname + ";Initial Catalog=" + dbname + ";User ID=" + username + ";Password=" + password + ";";
        }
    }

    
}

LuckLogsApp/Controllers/RaidLogsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LuckLogsApp.Models;
using LuckLogsApp.Models.ParseModels;
using LuckLogsApp.Models.ParseEnums;

using Amazon;
using Amazon.S3;
using Amazon.S3.Model;
using System.Configuration;
using System.Diagnostics;
using HtmlAgilityPack;
using System.Net.Http;
using System.Threading.Tasks;
using System.Xml.Serialization;
using System.IO;

namespace LuckLogsApp.Controllers
{
    public class RaidLogsController : ApplicationController
    {

       // private RaidLogDBContext db = new RaidLogDBContext();
        private static readonly string _awsAccessKey = ConfigurationManager.AppSettings["AWSAccessKey"];
        private static readonly string _awsSecretKey = ConfigurationManager.AppSettings["AWSSecretKey"];
        private static readonly string _bucketName = ConfigurationManager.AppSettings["Bucketname"];

        // GET: RaidLogs
        //[Authorize]
        public ActionResult Index()
        {
            //Database.SetInitializer(new DropCreateDatabaseIfModelChanges<RaidLogDBContext>());
            ViewModel model = new ViewModel();
            model.DbList = db.RaidLogs.ToList();
            model.PlList = playerDB.PlayerLogs.ToList();
            return View(model);
        }

        // GET: RaidLogs/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            ViewModel model = new ViewModel();
            model.DbList = db.RaidLogs.ToList();
            model.PlList = playerDB.PlayerLogs.ToList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RaidLog raidLog = db.RaidLogs.Find(id);
            if (raidLog == null)
            {
                return HttpNotFound();
            }
            TempData["Log"] = raidLog;
            return View(model);
        }

        // GET: RaidLogs/Delete/5
        //[Authorize]
        public ActionResult Delete(int? id)
        {
            ViewModel model = new ViewModel();
            model.DbList = db.RaidLogs.ToList();
            model.PlList = playerDB.PlayerLogs.ToList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RaidLog raidLog = db.RaidLogs.Find(id);
            if (raidLog == null)
            {
                return HttpNotFound();
            }
            TempData["Log"] = raidLog;
            return View(model);
        }

        // POST: RaidLogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RaidLog raidLog = db.RaidLogs.Find(id);
            if(raidLog.EVTCFile != null) { DeleteS3Item(raidLog.EVTCFile); }
            if (raidLog.HtmlFile != null) { DeleteS3Item(raidLog.HtmlFile); }
            db.RaidLogs.Remove(raidLog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        // GET: RaidLogs/Parse/5 ---------------------------------------------------------------------------------------------------------------------------------------
        //[Authorize]
        public ActionResult Parse(int? id)
        {
            ViewModel model = new ViewModel();
            model.DbList = db.RaidLogs.ToList();
            model.PlList = playerDB.PlayerLogs.ToList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RaidLog raidLog = db.RaidLogs.Find(id);
            if (raidLog == null)
            {
                return HttpNotFound();
            }
            //TempData["Log"] = raidLog;
            return View(model);
        }

        // POST: RaidLogs/Parse/5
        [HttpPost, ActionName("Parse")]
        [ValidateAntiForgeryToken]
        public ActionResult ParseConfirmed(int id)
        {
            bool p = ParseLog(id);
            if (p)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Error");
            }
           
        }
        public static byte[] StreamToBytes(Stream input)
        {
            byte[] buffer = new byte[16 * 1024];
            using (MemoryStream ms = new MemoryStream())
            {
                int read;
                while ((read = input.Read(buffer, 0, buffer.Length)) > 0)
                {
                    ms.Write(buffer, 0, read);
                }
                return ms.ToArray();
            }
        }


        // Private Methods
        private Stream origstream =  null;
        private MemoryStream stream = new MemoryStream();
        private void safeSkip(long bytes_to_skip)
        {

            while (bytes_to_skip > 0)
            {
                int dummyByte = stream.ReadByte();
                long bytes_actually_skipped = 1;
                if (bytes_actually_skipped > 0)
                {
                    bytes_to_skip -= bytes_actually_skipped;
                }
                else if (bytes_actually_skipped == 0)
                {
                    if (stream.ReadByte() == -1)
                    {
                        break;
                    }
                    else
                    {
                        bytes_to_skip--;
                    }
                }
            }
            
            return;
        }

        private int getbyte()
        {
            byte byt = Convert.ToByte(stream.ReadByte());
           // stream.Position++;

            return byt;
        }
        private int getShort()
        {
            byte[] bytes = new byte[2];
            for (int b = 0; b < bytes.Length; b++)
            {
                bytes[b] = Convert.ToByte(stream.ReadByte());
                //stream.Position++;
            }
            // return Short.toUnsignedInt(ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN).getShort());
            return BitConverter.ToUInt16(bytes,0);
        }

        private int getInt()
        {
            byte[] bytes = new byte[4];
            for (int b = 0; b < bytes.Length; b++)
            {
                bytes[b] = Convert.ToByte(stream.ReadByte());
               // stream.Position++;
            }
            //return ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN).getInt();
            return BitConverter.ToInt32(bytes,0);
        }

        private long getLong()
        {
            byte[] bytes = new byte[8];
            for (int b = 0; b < bytes.Length; b++)
            {
                bytes[b] = Convert.ToByte(stream.ReadByte());
               // stream.Position++;
            }

            // return ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN).getLong();
            return BitConverter.ToInt64(bytes,0);
        }

        private String getString(int length)
        {
            byte[] bytes = new byte[length];
            for(int b = 0;b < bytes.Length;b++) {
                bytes[b] = Convert.ToByte(stream.ReadByte());
               // stream.Position++;
            }
           
            string s = new String(System.Text.Encoding.UTF8.GetString(bytes).ToCharArray()).TrimEnd();
            if (s != null) {
                return s;
            }
            return "UNKNOWN";
        }

        private LogData log_data;
        private BossData boss_data;
        private AgentData agent_data = new AgentData();
        private SkillData skill_data = new SkillData();
        private CombatData combat_data = new CombatData();

        // Public Methods
        public LogData getLogData()
        {
            return log_data;
        }
        public BossData getBossData()
        {
            return boss_data;
        }
        public AgentData getAgentData()
        {
            return agent_data;
        }
        public SkillData getSkillData()
        {
            return skill_data;
        }
        public CombatData getCombatData()
        {
            return combat_data;
        }

        public bool ParseLog(int ID)
        {

            bool sucessfulParse = false;
            RaidLog raidLog = db.RaidLogs.Find(ID);
            WebClient client = new WebClient();
            origstream = client.OpenRead(raidLog.EVTCFile);
            origstream.CopyTo(stream);
            stream.Position = 0;
            
            TempData["Debug"] = "";
            
            parseBossData();
            parseAgentData();
            parseSkillData();
            parseCombatList();
            fillMissingData();

            origstream.Close();
            stream.Close();
            sucessfulParse = true;

            CreateHTML();
            return (sucessfulParse);
        }

        private void parseBossData()
        {
            // 12 bytes: arc build version
            String build_version = getString(12);
            this.log_data = new LogData(build_version);

            // 1 byte: skip
            safeSkip(1);

            // 2 bytes: boss instance ID
            int instid = getShort();

            // 1 byte: position
            safeSkip(1);

            //Save
           // TempData["Debug"] = build_version +" "+ instid.ToString() ;
            this.boss_data = new BossData(instid);
        }

        private void parseAgentData() {
            // 4 bytes: player count
            int player_count = getInt();
            //TempData["Debug"] += "player count:" + player_count.ToString();

            // 96 bytes: each player
            for (int i = 0; i < player_count; i++)
            {

LuckLogsApp/Views/RaidLogs/Delete.cshtml
@*@model LuckLogsApp.Models.RaidLog*@

@{
    ViewBag.Title = "Delete";
    var log = (LuckLogsApp.Models.RaidLog)TempData["Log"];
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RaidLog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            EVTCFile
        </dt>

        <dd>
           @log.EVTCFile
        </dd>

        <dt>
           HtmlFile
        </dt>

        <dd>
            @log.HtmlFile
        </dd>

        <dt>
            Boss name
        </dt>

        <dd>
            @log.BossName
        </dd>

        <dt>
            Sucess
        </dt>

        <dd>
            @log.Sucess

        </dd>

        <dt>
           Date Uploaded
        </dt>

        <dd>
            @log.Date
        </dd>

        <dt>
            KillTime
        </dt>

        <dd>
            @log.KillTime
        </dd>

        

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LuckLogsApp/Views/RaidLogs/Details.cshtml
@{
    ViewBag.Title = "Details";
    var log = (LuckLogsApp.Models.RaidLog)TempData["Log"];
}

<h2>Details</h2>

<div>
    <h4>RaidLog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            EVTC File
        </dt>

        <dd>
            @log.EVTCFile
        </dd>

        <dt>
           HtmlFile
        </dt>

        <dd>
            @log.HtmlFile
        </dd>

        <dt>
            Boss Name
        </dt>

        <dd>
            @log.BossName
        </dd>

        <dt>
            Success
        </dt>

        <dd>
            @log.Sucess
        </dd>

        <dt>
           Date Posted
        </dt>

        <dd>
            @log.Date
        </dd>

        <dt>
            KillTime
        </dt>

        <dd>
           @log.KillTime
        </dd>

        

    </dl>
</div>
<p>
    
    @Html.ActionLink("Back to List", "Index")
</p>

LuckLogsApp/Views/RaidLogs/Index.cshtml
@model LuckLogsApp.Models.ViewModel

@{
    ViewBag.Title = "Index";
}
<p>@Html.Raw( TempData["Debug"])</p>
<nav class="navbar navbar-default ">
    <div class="container-fluid">
        <ul class="nav navbar-nav navbar-right">
            <li><a href="#" data-toggle="modal" data-target="#uploadModal"><span class="glyphicon glyphicon-upload"></span>Upload </a></li>
        </ul>
</div>
    </nav>
        <h2>Logs Database</h2>
       <div class="alert alert-dismissible alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>Unless you are Admin please leave</strong> <br />
        </div>
        
        <table class="table">
            <tr>

                <th>Log ID</th>
                <th>
                    EVTCFile
                </th>
                <th>
                    HTMLFile
                </th>
                <th>
                    Boss
                </th>
                <th>
                    Success
                </th>
                <th>
                    Date
                </th>
                <th>
                    KillTime
                </th>
               
                <th></th>
            </tr>

            @foreach (var item in Model.DbList)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EVTCFile)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HtmlFile)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BossName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Sucess)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.KillTime)
                    </td>
                 
                    <td>
                        @*@Html.ActionLink("Edit", "Edit", new { id = item.ID }) |*@
                        @Html.ActionLink("Details", "Details", new { id = item.ID }) 
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                        @Html.ActionLink("Parse","Parse", new { id = item.ID })
                        @Html.ActionLink("Scrape", "Scrape", new { id = item.ID })
                        
                    </td>
                </tr>
            }

        </table>

        <!-- Upload Modal -->
        <div class="modal fade" id="uploadModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel3">
            <div class="modal-dialog" role="document">
                <div class="modal-content">

                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel3">Upload Logs</h4>
                    </div>

                    <div class="modal-body">
                        <h2>Drag and Drop EVTCs or htmls of raidheroes</h2>
                        <div id="dropArea">Drop files here</div>
                        <h4>Uploaded Files:</h4>
                        <ul class="list-group" id="uploadList"></ul>
                        <h5>@Html.ActionLink("Reload Page", "Index", "RaidLogs")</h5>
                    </div>

                </div>
            </div>
        </div>
        <script type="text/javascript">
        $(function () {
            $('#dropArea').filedrop({
                url: '@Url.Action("UploadProcess")',
                allowedfileextensions: ['.evtc' ,'.html'],
                paramname: 'files',
                maxfiles: 15,
                maxfilesize: 20, // in MB
                dragOver: function () {
                    $('#dropArea').addClass('active-drop');
                },
                dragLeave: function () {
                    $('#dropArea').removeClass('active-drop');
                },
                drop: function () {
                    $('#dropArea').removeClass('active-drop');
                },
                afterAll: function (e) {
                    $('#dropArea').html('file(s) uploaded successfully');
                },
                uploadFinished: function (i, file, response, time) {
                    $('#uploadList').append('<li class="list-group-item">'+file.name+'</li>')
                }
            })
        })
        </script>
        

LuckLogsApp/Views/RaidLogs/Parse.cshtml
@*@model LuckLogsApp.Models.RaidLog*@

@{
    ViewBag.Title = "Parse";
    var log = (LuckLogsApp.Models.RaidLog)TempData["Log"];
}

<h2>Parse</h2>

<h3>Parse this file?</h3>
<div>
    <h4>RaidLog</h4>
    <hr />
    @*<dl class="dl-horizontal">
        <dt>
            EVTCFile
        </dt>

        <dd>
           @log.EVTCFile
        </dd>

        <dt>
           HtmlFile
        </dt>

        <dd>
            @log.HtmlFile
        </dd>

        <dt>
            Boss name
        </dt>

        <dd>
            @log.BossName
        </dd>

        <dt>
            Sucess
        </dt>

        <dd>
            @log.Sucess

        </dd>

        <dt>
           Date Uploaded
        </dt>

        <dd>
            @log.Date
        </dd>

        <dt>
            KillTime
        </dt>

        <dd>
            @log.KillTime
        </dd>

        

    </dl>*@

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Parse" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LuckLogsApp/Views/RaidLogs/Scrape.cshtml
@*@model LuckLogsApp.Models.RaidLog*@

@{
    ViewBag.Title = "Scrape";
    var log = (LuckLogsApp.Models.RaidLog)TempData["Log"];
}

<h2>Scrape</h2>

<h3>Scrape this file?</h3>
<div>
    <h4>RaidLog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            EVTCFile
        </dt>

        <dd>
          @log.EVTCFile
        </dd>

        <dt>
           HtmlFile
        </dt>

        <dd>
            @log.HtmlFile
        </dd>

        <dt>
            Boss name
        </dt>

        <dd>
            @log.BossName
        </dd>

        <dt>
            Sucess
        </dt>

        <dd>
            @log.Sucess

        </dd>

        <dt>
           Date Uploaded
        </dt>

        <dd>
            @log.Date
        </dd>

        <dt>
            KillTime
        </dt>

        <dd>
            @log.KillTime
        </dd>

        

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Scrape" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LuckLogsApp/Views/RaidLogs/Skills.cshtml
@{
    ViewBag.Title = "Skills";
}

<h2>Weapon Skills</h2>
<p>A list of skills that this website gathers from the GW2API in order to determine what weapon a player was usieng based on skills</p>
<p>@TempData["Debug"]</p>
<p>@Html.Raw(TempData["Skills"])</p>